version: "3.8"
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: apps/backend/Dockerfile
  #   container_name: backend
  #   ports:
  #     - "4000:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
  #   depends_on:
  #     - db

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: apps/frontend/Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - API_URL=http://backend:3001
  #   depends_on:
  #     - backend

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
