name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the backend Docker image
      run: docker build . --file ./apps/backend/Dockerfile --tag tinder-like-app-backend:$(date +%s)

    - name: Build the frontend Docker image
      run: docker build . --file ./apps/frontend/Dockerfile --tag tinder-like-app-frontend:$(date +%s)
